title: Hitham Husham # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  <footer>

  <section class="contact">
      <h3 class="contact-title">Contact me</h3>
      <ul>
        
          <li>
          <a href="https://twitter.com/artemsheludko_" target="_blank">
          <i class="fa fa-twitter" aria-hidden="true">
          </i>
          </a>
          </li>
        
        
          <li>
          <a href="https://facebook.com/" target="_blank">
          <i class="fa fa-facebook" aria-hidden="true">
          </i>
          </a>
          </li>
        
        
          <li class="github">
          <a href="http://github.com/artemsheludko" target="_blank">
          <i class="fa fa-github">
          </i>
          </a>
          </li>
        
        
          <li class="linkedin">
          <a href="https://in.linkedin.com/" target="_blank">
          <i class="fa fa-linkedin" aria-hidden="true">
          </i>
          </a>
          </li>
  </footer>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
