title: Hitham Husham # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  :palestinian_territories:
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  <br><br>
  
  <div class="social-list pl-0 mb-0">
                    <a href="https://twitter.com/mobirise" target="_blank">
                        <span class="px-2 socicon-twitter socicon mbr-iconfont mbr-iconfont-social" media-simple="true"></span>
                    </a>
                    <a href="https://www.facebook.com/pages/Mobirise/1616226671953247" target="_blank">
                        <span class="px-2 socicon-facebook socicon mbr-iconfont mbr-iconfont-social" media-simple="true"></span>
                    </a>
                    <a href="https://instagram.com/mobirise" target="_blank">
                        <span class="px-2 socicon-instagram socicon mbr-iconfont mbr-iconfont-social" media-simple="true"></span>
                    </a>
                    <a href="https://www.youtube.com/c/mobirise" target="_blank">
                        <span class="px-2 socicon-youtube socicon mbr-iconfont mbr-iconfont-social" media-simple="true"></span>
                    </a>
                    <a href="https://plus.google.com/u/0/+Mobirise" target="_blank">
                        <span class="px-2 socicon-googleplus socicon mbr-iconfont mbr-iconfont-social" media-simple="true"></span>
                    </a>
                    <a href="https://www.behance.net/Mobirise" target="_blank">
                        <span class="px-2 socicon-behance socicon mbr-iconfont mbr-iconfont-social" media-simple="true"></span>
                    </a>
                </div>
 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
